project:
  type: book

execute:
    enabled: false

book:
  title: "Fundamentals of Research Data Management"
  author:
    - name: Christine Staiger
      orcid: 0000-0002-6754-7647
    - name: Neha Moopen
      orcid: 0000-0003-1412-4402
  date: last-modified

  sidebar:
    style: "docked"
    background: "#CDE498"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source code
            url:  https://github.com/chStaiger/rdm-fundamentals
          - text: Report an issue
            url:  https://github.com/chStaiger/rdm-fundamentals/issues

  chapters:
    - index.qmd
    - definitions.qmd
    - data-lifecycle.qmd
  
    - part: "THE HOLY TRINITY OF RDM"
      chapters:
        - digital-object.qmd
        - files.qmd
        - metadata.qmd
        - pids.qmd

    - storage-infrastructure.qmd
    
    - part: "COMPONENTS OF RDM INFRASTRUCTURE"
      chapters:
      - rdm-infra-intro.qmd
      - digital-object-infrastructure.qmd
      - data-repositories.qmd
      - policy-engines.qmd
      - metadata-portals.qmd
      - pid-services.qmd
      - rdm-platform.qmd
    - infrastructure-design.qmd
    - summary.qmd
    - references.qmd
  
  page-footer:
    left: "©️ [Creative Commons Attribution 4.0 International](https://github.com/chStaiger/rdm-fundamentals/blob/main/LICENSE.md)"
    right: "Built with [Quarto](https://quarto.org/) & [GitHub](https://github.com/)<br>Maintained with 🍵 & ☕"
  
bibliography: references.bib

filters:
  - debruine/quarto-glossary


glossary:
  path: glossary.yml
  popup: hover
  show: true


format:
  html:
    theme: cosmo
    css: 
      - css_files/callout.css
      - css_files/toc.css
      - css_files/hyperlinks.css
    number-sections: false
    mermaid:
      theme: forest


