project:
  type: book

execute:
    enabled: false

book:
  title: "Principles of Research Data Management Architecture"
  author:
    - name: Christine Staiger
      orcid: 0000-0002-6754-7647
    - name: Neha Moopen
      orcid: 0000-0003-1412-4402
  date: last-modified

  sidebar:
    style: "docked"
    background: "#CDE498"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source code
            url:  https://github.com/rdm-foundations/rdm-architecture
          - text: Report an issue
            url:  https://github.com/rdm-foundations/rdm-architecture/issues

  chapters:
    - index.qmd
    - preface.qmd
    - definitions.qmd
    - data-lifecycle.qmd
  
    - part: "THE HOLY TRINITY OF RDM"
      chapters:
        - digital-object.qmd
        - files.qmd
        - metadata.qmd
        - pids.qmd

    - storage-infrastructure.qmd
    
    - part: "COMPONENTS OF RDM INFRASTRUCTURE"
      chapters:
        - rdm-infra-intro.qmd
        - digital-object-infrastructure.qmd
        - data-repositories.qmd
        - policy-engines.qmd
        - metadata-portals.qmd
        - pid-services.qmd
    - rdm-platform.qmd
    - do-continuity.qmd
    - references.qmd
  
  page-footer:
    left: "©️ [Creative Commons Attribution 4.0 International](https://github.com/rdm-foundations/rdm-architecture/blob/main/LICENESE.md)<br>&ensp;&ensp;&ensp;[Authors & Contributors](https://github.com/rdm-foundations/rdm-architecture#contributors)"
    right: "Built with [Quarto](https://quarto.org/) & [GitHub](https://github.com/)<br>Maintained with 🍵 & ☕"  

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: 
      - css_files/callout.css
      - css_files/toc.css
      - css_files/hyperlinks.css
      - css_files/figure_margins.css
    number-sections: false
    mermaid:
      theme: forest
    grid:
      sidebar-width: 400px
    comments: 
      utterances: 
        repo: rdm-foundations/rdm-architecture


